// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpixanjrhvwrhsacamwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwaXhhbmpyaHZ3cmhzYWNhbXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTk4OTQsImV4cCI6MjA3MzMzNTg5NH0.vFz6yHlz0444_NqsuQACgGcs_TjazOtUpGDP7BP6mu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});